openapi: "3.0.0"
info:
  version: "1.0"
  title: "My awesome REST API"
  description: "Does some cool stull that people really like."
#servers:
#    - url: "http://localhost:9000"
#      description: Test server

tags:
- name: "api"
  description: Swagger API blueprint

paths:
  /api:
    summary: The Swagger API blueprint
    description: The Swagger API blueprint, as YAML or HTML
    get:
      tags:
        - "api"
      summary: The Swagger API
      operationId: apiYaml
      x-marklogic-main-module: /swagger/code/filter-swagger.xqy
      responses:
        200:
          description: Good response, returns interface spec as OpenAPI Swagger or HTML
          content:
              text/x-yaml:
                example: 'openapi: "3.0.0"
                  info:
                    version: "1.0"
                    title: "My Awesome REST API"
                    description: "Does some cool stuff that people really like."'
              text/html:
                example: '<html>
                  ...
                  </html>'
  /simple-module-get:
    summary: Test Module Get
    description: Endpoint
    get:
      tags:
        - "Test APIs"
      summary: Endpoint to test main module trigger
      x-marklogic-main-module: /swagger/sample/test-module-get.xqy
      responses:
        200:
          description: Good response
          content:
              text/plain:
                example: 'Module GET'
