openapi: "3.0.0"
info:
  version: "1.0"
  title: "My awesome REST API"
  description: "Does some cool stull that people really like."
servers:
    - url: "http://localhost:10000"
      description: Test server

tags:
- name: "api"
  description: Swagger API blueprint

paths:
  /api:
    description: The Swagger API blueprint, as YAML or HTML
    get:
      summary: The Swagger API
      operationId: apiYaml
      x-marklogic-handler: /swagger/code/filter-swagger.xqy
      responses:
        200:
          description: Good response, returns interface spec as OpenAPI Swagger or HTML
          content:
              text/x-yaml:
                example: 'openapi: "3.0.0"
                  info:
                    version: "1.0"
                    title: "My awesome REST API"
                    description: "Does some cool stull that people really like."'
              text/html:
                example: '<html>
                  ...
                  </html>'
